version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: K5.2
  labels:
  - "5.2"
  - dependencies
  ignore:
  - dependency-name: symfony/console
    versions:
    - 5.2.2
  - dependency-name: symfony/process
    versions:
    - 5.2.2
  - dependency-name: symfony/filesystem
    versions:
    - 5.2.2
  - dependency-name: symfony/finder
    versions:
    - 5.2.2
  - dependency-name: symfony/yaml
    versions:
    - 5.2.2
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.1
  - dependency-name: codeception/codeception
    versions:
    - 4.1.15
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: K6.0
  labels:
  - "6.0"
  - dependencies
  ignore:
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.1
    - 2.18.5
  - dependency-name: codeception/codeception
    versions:
    - 4.1.15
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
